
name: publish
on:
  push:
    branches: [ release ]
  release:
    types: [ published ]

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          10.0.x
    - name: Pack
      run: dotnet pack -c Release
    - name: Publish package
      run: dotnet nuget push --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json artifacts/package/release/*.nupkg